language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls

env:
  global:
    - secure: "a3SSB2ZexPd9u6bOFiKjB4LX1FSvsRCz1RQHdHPYc6Z8pYNqAL/yMXCMsI9XtWOAOjjgdZwpBm3yG3FZggchLXWmJnHfnP9j4f5niDeQozlzCZDHNRE0GxnaTB8Ogah1zJPyT9pik57L5uai8oZUP+x5Kh1MSV7sTBICQcuAEjc="
    - secure: "VrtXnXvCCahqWDcrfZgClsURVOe3nDeS0F8K7LTjS8FuzE0HHHQGO3oLpnh7No86gRr5fuRAh80jhAstmM1uywcAPQFphN8OBtUqCjlMvOxHYpyk1uD4k1RaK92a8wKP8C7PW+1N3UYbz9xUPoUclPBJ2+FOts93my9uDnhdD1U="
    - secure: "YBNYOpmdOjfqjhS4EbAlaK4qL3Nc+QETiJBJ4iaa/Nae2NeWYvBSR7NS1eT+5/2l45b3a0mVRYCWWY2MNq1RVlU/49vvgkDzfHFl4MpkakDPiosHNxF8Rb/vm8WOgFZ4gTQcWMAKtfIU+svEienjcXSYRn84e0Z/u41QbCHoJ5A="
    - secure: "bCLWilVf4kOvKEEdUeJWC721Vl9DEJcorZNk7bpBZUx3Lupj7FtrXMXmEAPiGlLf92SXV0mRbgYF/D9faIq8mj3PJGmgeN6go1e661G8B7qvuRSIY1n+3XGhKxi5Rf8AF6ZYVd87gKYVfvSdk6NN1FKO3kwUJtVoXp6pIENwPF0="
    - secure: "N4NcDmWFkHACgL3Gm+ZlNjGb7RYwf185QrSkUZQ6DZxEWrmzBglbuPZAfez9avl0shM2FXnSWxq0zGRyewJFuYHEk7sg/YbQqXVIbwe0DJCsSK49IwLJHIzmRoSLETQSbUoqg2a82eIwZBnMlQmGpuvopdx1Ih0IRiBqDXVlmMo="
